# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
# before_script:
#   - apt-get update -yqq
#   - apt-get install -yqq --no-install-recommends build-essential

build:cargo:
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - rustc --version && cargo --version
    - cargo build

# Use cargo to test the project
test:cargo:
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose